"""
Medical Report Generator

This module is responsible for generating structured
medical reports from AI predictions using Google's
Gemini Large Language Model.
"""

from google import genai
from google.genai import types

from configs.config import cfg

from src.inference.postprocess import PredictionResult
from src.llm.prompt_builder import build_prompt
from src.llm.schemas import MedicalReport
from src.utils.logger import get_logger


logger = get_logger(__name__)


# ==========================================================
# Gemini Client
# ==========================================================

client = genai.Client(
    api_key=cfg.GEMINI_API_KEY
)


# ==========================================================
# Report Generator
# ==========================================================

def generate_medical_report(
    prediction: PredictionResult,
) -> MedicalReport:
    """
    Generate a structured medical report from an AI prediction.

    Parameters
    ----------
    prediction : PredictionResult
        Output generated by the image classification model.

    Returns
    -------
    MedicalReport
        Structured medical report validated using Pydantic.
    """

    logger.info("Building prompt for Gemini...")

    prompt = build_prompt(prediction)

    logger.info(
        "Generating medical report using %s...",
        cfg.LLM_MODEL,
    )

    try:

        response = client.models.generate_content(
            model=cfg.LLM_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.4,
                top_p=0.95,
                top_k=40,
                max_output_tokens=2500,
                response_mime_type="application/json",
                response_schema=MedicalReport,
            ),
        )

        logger.info("Response text: %s", response.text)
        logger.info("Parsed response: %s", response.parsed)

        if response.parsed is None:
            raise RuntimeError(
                f"Gemini returned an unparsable response.\n"
                f"Raw response:\n{response.text}"
            )

        return response.parsed

    except Exception as e:
        logger.exception("Medical report generation failed.")
        raise RuntimeError(
            f"Gemini Report Generation Failed: {e}"
        ) from e