/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#acedff",
        "inverse-primary": "#b4c5ff",
        error: "#ba1a1a",
        "tertiary-container": "#00788c",
        "on-surface-variant": "#434655",
        "on-secondary-fixed": "#002113",
        outline: "#737686",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "primary-container": "#2563eb",
        "surface-dim": "#d8dadc",
        surface: "#f7f9fb",
        "on-tertiary-container": "#d7f6ff",
        background: "#f7f9fb",
        "on-error-container": "#93000a",
        "surface-tint": "#0053db",
        "secondary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "on-primary-container": "#eeefff",
        tertiary: "#005e6e",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed": "#001f26",
        "surface-bright": "#f7f9fb",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "outline-variant": "#c3c6d7",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed-dim": "#4edea3",
        "inverse-surface": "#2d3133",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-secondary-container": "#00714d",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "secondary-container": "#6cf8bb",
        "on-tertiary-fixed-variant": "#004e5c",
        primary: "#004ac6",
        secondary: "#006c49",
        "on-secondary-fixed-variant": "#005236",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "16px",
        lg: "40px",
        base: "4px",
        md: "24px",
        xs: "8px",
        gutter: "24px",
        xl: "64px",
        margin: "32px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        display: ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      maxWidth: {
        "content": "1440px",
      },
    },
  },
  plugins: [],
}
